const languages = [
  { index: 0, code: "en", name: "English" },
  { index: 1, code: "eu", name: "Basque" },
  { index: 2, code: "es", name: "Spanish" },
  { index: 3, code: "fr", name: "French" },
  { index: 4, code: "de", name: "German" },
  { index: 5, code: "it", name: "Italian" },
  { index: 6, code: "pt", name: "Portuguese" },
  { index: 7, code: "nl", name: "Dutch" },
  { index: 8, code: "sv", name: "Swedish" },
  { index: 9, code: "no", name: "Norwegian" },
  { index: 10, code: "da", name: "Danish" },
  { index: 11, code: "fi", name: "Finnish" },
  { index: 12, code: "is", name: "Icelandic" },
  { index: 13, code: "pl", name: "Polish" },
  { index: 14, code: "ru", name: "Russian" },
  { index: 15, code: "uk", name: "Ukrainian" },
  { index: 16, code: "el", name: "Greek" },
  { index: 17, code: "tr", name: "Turkish" },
  { index: 18, code: "ar", name: "Arabic" },
  { index: 19, code: "he", name: "Hebrew" },
  { index: 20, code: "zh", name: "Chinese" },
  { index: 21, code: "ja", name: "Japanese" },
  { index: 22, code: "ko", name: "Korean" },
  { index: 23, code: "hi", name: "Hindi" },
  { index: 24, code: "ur", name: "Urdu" },
  { index: 25, code: "af", name: "Afrikaans" },
  { index: 26, code: "sq", name: "Albanian" },
  { index: 27, code: "am", name: "Amharic" },
  { index: 28, code: "hy", name: "Armenian" },
  { index: 29, code: "az", name: "Azerbaijani" },
  { index: 30, code: "be", name: "Belarusian" },
  { index: 31, code: "bn", name: "Bengali" },
  { index: 83, code: "yi", name: "Yiddish" },
  { index: 84, code: "yo", name: "Yoruba" },
  { index: 85, code: "zu", name: "Zulu" },
];

export default languages;
